name: cwt_ecommerce_ui_kit
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

#--------------- PACKAGES ------------------#
dependencies:
  capped_progress_indicator: ^0.0.2
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.9.3
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  flutter:
    sdk: flutter
  
  flutter_native_splash: ^2.3.3
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.7
  get: ^4.6.5
  get_storage: ^2.1.1
  http: ^1.1.0
  iconsax: ^0.0.8
  intl: ^0.18.1
  logger: ^2.0.1
  readmore: ^2.2.0
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#272727"
  image: assets/logos/t-store-splash-logo-black.png
  image_dark: assets/logos/t-store-splash-logo-white.png

  android_12:
    color: "#FFFFFF"
    color_dark: "#272727"
    image: assets/logos/t-store-splash-logo-black.png
    image_dark: assets/logos/t-store-splash-logo-white.png




    






  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/content/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/icons/categories/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
